version: '3.1'
services:
  db:
    image: mariadb
    restart: always
    container_name: javaApi-db
    ports:
      - "3350:3306"
    environment:
      MYSQL_ROOT_PASSWORD: javaApi
      MYSQL_USER: javaApi.user
      MYSQL_PASSWORD: javaApi.password123
      MYSQL_DATABASE: javaApiDoctor
    volumes:
      - "./.docker/dbdata:/var/lib/mysql"





